 //LOCALHOST 
 ###
GET http://localhost:8080/contacts 
###
GET http://localhost:8080/contacts/632893e28fae4a870db1d2a8 
###
GET http://localhost:8080/contacts/632894978fae4a870db1d2a9
###
GET http://localhost:8080/contacts/6328965c8fae4a870db1d2aa


// PRODUCTION Deploy 
###
GET https://cse341-instructor.herokuapp.com/contacts 
### 
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b2 
### 
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b3 
### 
GET https://cse341-instructor.herokuapp.com/contacts/622023f642f9ab4cd6e060b4
