 //LOCALHOST 
 ###
GET http://localhost:8080/contacts 
###
GET http://localhost:8080/contacts/632893e28fae4a870db1d2a8 
###
GET http://localhost:8080/contacts/632894978fae4a870db1d2a9
###
GET http://localhost:8080/contacts/6328965c8fae4a870db1d2aa


// PRODUCTION Deploy 
###
GET https://ipulotu-ces341.onrender.com/contacts 
### 
GET https://ipulotu-ces341.onrender.com/contacts/632893e28fae4a870db1d2a8
### 
GET https://ipulotu-ces341.onrender.com/contacts/632894978fae4a870db1d2a9 
### 
GET https://ipulotu-ces341.onrender.com/contacts/6328965c8fae4a870db1d2aa
