 //LOCALHOST 
 ###
GET http://localhost:8080/contacts 
###
GET http://localhost:8080/contacts/632893e28fae4a870db1d2a8 

### Creating a contact
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Bill",
    "lastName": "cloolio",
    "email": "iammrewn@yahoo.com",
    "favoriteColor": "gray",
    "birthday.": "1999-06-01"
}

### Deleteing a contact
DELETE http://localhost:8080/contacts/6331d40cfafc0f353c485ca7 HTTP/1.1

### Update a contact

PUT http://localhost:8080/contacts/6331d40cfafc0f353c485ca7 HTTP/1.1
Content-Type: application/json

{
    "firstName": "will",
    "lastName": "Rloolio",
    "email": "Rullon@yahoo.com",
    "favoriteColor": "white",
    "birthday.": "2002-06-01T00:00:00.000Z"
}

// PRODUCTION Deploy 
###
GET https://ipulotu-ces341.onrender.com/contacts 
### 
GET https://ipulotu-ces341.onrender.com/contacts/632893e28fae4a870db1d2a8
### 
GET https://ipulotu-ces341.onrender.com/contacts/632894978fae4a870db1d2a9 
### 
GET https://ipulotu-ces341.onrender.com/contacts/6328965c8fae4a870db1d2aa
