 //LOCALHOST 
 ### get all contacs
GET http://localhost:8080/cookbook

### Get one cotact
GET http://localhost:8080/cookbook/634d733f47a5se00362ef830 

### Creating a contact
POST http://localhost:8080/cookbook HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "description": "test",
    "type": "test",
    "servings": "test",
    "timeToCook": "test",
    "ingredient1Name":"test",
    "ingredient1Amount": "test",
    "ingredient2Name":"test",
    "ingredient2Amount": "test"
    
}

### Deleteing a contact
DELETE http://localhost:8080/cookbook/634dd6cedc11d2b043d3875e HTTP/1.1

### Update a contact
PUT http://localhost:8080/cookbook/634dd6cedc11d2b043d3875e HTTP/1.1
Content-Type: application/json

{
    "name": "tesft",
    "description": "tesdft",
    "type": "tsdfest",
    "servings": "test",
    "timeToCook": "test",
    "ingredient1Name":"test",
    "ingredient1Amount": "test",
    "ingredient2Name":"test",
    "ingredient2Amount": "test"
}




// PRODUCTION Deploy 
### Get all contacts
 ### get all contacs
GET https://ipulotu-cookbook.onrender.com/cookbook

### Get one cotact
GET https://ipulotu-cookbook.onrender.com/cookbook/634594847a0af984f36860c8 

### Creating a contact
POST https://ipulotu-cookbook.onrender.com/cookbook HTTP/1.1
Content-Type: application/json

{
    "name": "test",
    "description": "test",
    "type": "test",
    "servings": "test",
    "timeToCook": "test",
    "ingredient1Name":"test",
    "ingredient1Amount": "test",
    "ingredient2Name":"test",
    "ingredient2Amount": "test"
    
}

### Deleteing a contact
DELETE https://ipulotu-cookbook.onrender.com/cookbook/634594847a0af984f36860c8 HTTP/1.1

### Update a contact
PUT https://ipulotu-cookbook.onrender.com/cookbook/634594847a0af984f36860c8 HTTP/1.1
Content-Type: application/json

{
    "name": "tesft",
    "description": "tesdft",
    "type": "tsdfest",
    "servings": "test",
    "timeToCook": "test",
    "ingredient1Name":"test",
    "ingredient1Amount": "test",
    "ingredient2Name":"test",
    "ingredient2Amount": "test"
}
